Missing several changes on service and index.ts
vtex/vtex-courses pull request #142
Opened 2021-05-28 15:42 UTC by fabriziofbarros

#### What is the purpose of this pull request?
Instructions are missing important elements

#### What problem is this solving?
Really make this solution works

#### Types of changes
- [ ] Content fix
- [ ] Answer sheet fix
- [ ] Course refactor
- [ ] New course :rocket:
- [X] Script bug fix
- [ ] Script feature

2021-06-10 15:12 UTC, brunoamui requested changes

2021-06-10 15:12 UTC, brunoamui commented on courses/service-course/steps/04_clients-analytics/pt.md
> +7. Agora, é necessário fazer que a aplicação conheça implemente o Client do analytics recém criado e tenhamos uma rota para acessá-lo. Para fazer isso, há um arquivo dentro do diretório `/node` chama
```suggestion
7. Agora é necessário fazer que a aplicação importe e registre o Client do analytics recém criado. Dessa forma, teremos uma rota para acessá-lo. É comum que façamos isso no arquivo `index.ts` da pasta `/node` :
```

2021-06-10 15:12 UTC, brunoamui commented on courses/service-course/steps/04_clients-analytics/pt.md
> +4. Também é necessário modificar o arquivo `service.json` para incluirmos a rota ao serviço.
```suggestion
4. Também é necessário modificar o arquivo `service.json` e incluir a rota ao serviço.
```

2022-07-18 13:54 UTC, fabianaferreira requested changes
We need to add the new steps to the English files as well. @brunoamui, can we get some help here? Thanks!

2025-10-29 20:28 UTC, closed without merging