Corrected import from the store-block-template
vtex/vtex-courses pull request #160
Opened 2021-08-13 11:37 UTC by jhelison

#### What is the purpose of this pull request?

Typo correction.

#### What problem is this solving?

Fixed a typo.

#### Types of changes

- [x] Content fix
- [ ] Answer sheet fix
- [ ] Course refactor
- [ ] New course :rocket:
- [x] Script bug fix
- [ ] Script feature

2021-09-30 13:01 UTC, fabianaferreira requested changes
LGTM! However, it's necessary to change this for the other languages as well. Do you think you can do it, @jhelison?

cc @georgebrindeiro

2021-09-30 14:30 UTC, jhelison commented
Added the fix to the english file

2022-04-27 13:59 UTC, fabianaferreira approved these changes

2022-07-18 13:47 UTC, fabianaferreira approved these changes
LGTM

2022-07-18 13:54 UTC, merged