Adding "Calling Commerce APIs" couse
vtex/vtex-courses pull request #32
Opened 2020-09-11 16:16 UTC by lucis

2020-09-17 19:46 UTC, FabianaFerreira commented on courses/calling-commerce-apis/01_introduction/pt.md
> +- É importante que você tenha finalizado o **VTEX IO Service Course**, que explica como funcionam os serviços de backend dentro do VTEX IO.
```suggestion
- É importante que você tenha finalizado o **VTEX IO Service Course**, que explica como funcionam os serviços de _backend_ dentro do VTEX IO.
```

2020-09-17 19:49 UTC, FabianaFerreira commented on courses/calling-commerce-apis/04_using-client/pt.md
> +> O termo Stock Keeping Unit (SKU), em português Unidade de Manutenção de Estoque está ligado à logística de armazém e designa os diferentes itens do estoque, estando normalmente associado a um códig
```suggestion
> O termo Stock Keeping Unit (SKU), em português Unidade de Manutenção de Estoque, está ligado à logística de armazém e designa os diferentes itens do estoque, estando normalmente associado a um código identificador. _(Wikipedia)_
```

2020-09-17 19:50 UTC, FabianaFerreira commented on courses/calling-commerce-apis/04_using-client/pt.md
> +        "path": "/api/catalog*"
```suggestion
        "path": "/api/catalog/*"
```

2020-09-17 19:51 UTC, FabianaFerreira commented on courses/calling-commerce-apis/challenge.md
> +Agora, ao invés de reutilizar um Client do pacote `@vtex/clients`, **crie o seu próprio Client** seguindo os passos [deste material]().
Era para estar sem link mesmo?

2020-09-17 19:52 UTC, FabianaFerreira requested changes
Just a few comments, but it's amazing! 🚀

2020-09-17 19:56 UTC, lucis commented on courses/calling-commerce-apis/challenge.md
> +Agora, ao invés de reutilizar um Client do pacote `@vtex/clients`, **crie o seu próprio Client** seguindo os passos [deste material]().
Não, vou corrigir haha Essa parte escrevi sem internet, aí ainda vou complementar com um link da API real para o desafio e adicionar este link

2020-09-17 19:59 UTC, juliarocha requested changes
:noice mas cade os gabaritos?

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/01_introduction/pt.md
> +- Esperamos também que você tenha aprendido o conceito de Client nos serviços.
```suggestion
- Esperamos também que você tenha aprendido o conceito de _Client_ nos serviços.
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/01_introduction/pt.md
> +- Como utilizar estes Clients para fazer requisições em uma aplicação do VTEX IO.
```suggestion
- Como reusar _Clients_ disponíveis na comunidade.
- Como utilizar estes _Clients_ para fazer requisições em uma aplicação do VTEX IO.
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/03_importing-client/pt.md
> +Neste passo você aprenderá como buscar Clients já prontos que abstraem as APIs de Core Commerce, além de como importá-los para sua app no VTEX IO. Importaremos o client `Catalog` que permitirá que bu
```suggestion
Neste passo você aprenderá como buscar _Clients_ já prontos que abstraem as APIs de Core Commerce, além de como importá-los para sua app no VTEX IO. Importaremos o _client_ `Catalog` que permitirá que busquemos detalhes sobre um SKU dentro da plataforma VTEX.
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/03_importing-client/pt.md
> +Caso você não encontre o Client que você deseja para um serviço de Core Commerce da VTEX, recomendamos que você **envie um Pull Request** para o repositório `commerce-clients`. Ficaremos felizes em r
```suggestion
Caso você não encontre o _Client_ que você deseja para um serviço de Core Commerce da VTEX, recomendamos que você **envie um Pull Request** para o repositório `commerce-clients`. Ficaremos felizes em revisar e, eventualmente, mergear sua contribuição.
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/03_importing-client/pt.md
> +Mas, caso o serviço que você esteja tentando acessar seja um provedor externo (ex: API do Here Maps), recomendamos que você crie o Client na sua própria app seguindo [estes passos](https://www.notion
```suggestion
Mas, caso o serviço que você esteja tentando acessar seja um provedor externo (ex: API do Here Maps), recomendamos que você crie o _Client_ na sua própria app seguindo [estes passos](https://www.notion.so/How-to-use-and-create-Clients-on-VTEX-IO-1dbd20c928c642d0ba059d5efbe7874b).
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/03_importing-client/pt.md
> +Vamos agora importar um Client do módulo **Catalog** em nossa app. Para isso, utilizaremos a app [`service-example`](https://github.com/vtex-apps/service-example) como modelo. Caso você ainda não ten
```suggestion
Vamos agora importar um _Client_ do módulo **Catalog** em nossa app. Para isso, utilizaremos a app [`service-example`](https://github.com/vtex-apps/service-example) como modelo. Caso você ainda não tenha essa aplicação clonada locamente por outro curso, rode o seguinte comando:
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/03_importing-client/pt.md
> +Como o Client que usaremos é oferecido no pacote de Commerce Clients, vamos realizar a instalação. **Dentro da pasta `node`, rode o seguinte comando:**
```suggestion
Como o _Client_ que usaremos é oferecido no pacote de _Commerce Clients_, vamos realizar a instalação. **Dentro da pasta `node`, rode o seguinte comando:**
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/03_importing-client/pt.md
> +Agora que o pacote foi instalado, precisamos configurar o Client para utilizá-lo nos _resolvers_  e _middlewares_ de nossa app. Para isso, precisamos abrir o arquivo `node/clients/index.ts` e:
```suggestion
Agora que o pacote foi instalado, precisamos configurar o _Client_ para utilizá-lo nos _resolvers_  e _middlewares_ de nossa app. Para isso, precisamos abrir o arquivo `node/clients/index.ts` e:
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/04_using-client/pt.md
> +Já que o app `service-example` já exporta uma rota pública para testes (`https://{workspace}--{account}.myvtex.com/_v/status/:code`), iremos utilizá-la para testar realizar uma chamada utilizando o C
```suggestion
Já que o app `service-example` já exporta uma rota pública para testes (`https://{workspace}--{account}.myvtex.com/_v/status/:code`), iremos utilizá-la para testar realizar uma chamada utilizando o _Client_ de _Catalog_. Iremos usar o parâmetro `code` como o nosso "ID do Sku" para rapidamente testarmos o nosso _Client_.
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/04_using-client/pt.md
> +Como vimos no passo anterior, agora já temos disponível os métodos do nosso Client em `ctx.clients.catalog`. Para utilizá-lo, precisaremos chamar os métodos em algum _middleware_ de nossa app.
```suggestion
Como vimos no passo anterior, agora já temos disponível os métodos do nosso _Client_ em `ctx.clients.catalog`. Para utilizá-lo, precisaremos chamar os métodos em algum _middleware_ de nossa app.
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/04_using-client/pt.md
> +- Extraindo `catalog` do contexto que é recebido nas funções de middleware. Isso é um atalho para não precisarmos chamar `ctx.clients.catalog`. Saiba mais sobre Destructuring [aqui](https://developer
```suggestion
- Extraindo `catalog` do contexto que é recebido nas funções de _middleware_. Isso é um atalho para não precisarmos chamar `ctx.clients.catalog`. Saiba mais sobre Destructuring [aqui](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/04_using-client/pt.md
> +- Chamando o método `getSkuById` do Client Catalog. Este método irá, internamente, chamar o endpoint relativo no módulo do catálogo, repassando o parâmetro que estamos passando (`code`) como o ID do
```suggestion
- Chamando o método `getSkuById` do _Client Catalog_. Este método irá, internamente, chamar o endpoint relativo no módulo do catálogo, repassando o parâmetro que estamos passando (`code`) como o ID do SKU a ser buscado. Lembrando que esta é uma chamado assíncrona, então precisamos adicionar o `await` logo antes para esperá-la.
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/04_using-client/pt.md
> +Isso permitirá que sua app faça chamadas para essa URL, especificamente. Por mais que você não tenha precisado colocá-la em seu código, é ela que é usada internamente pelo Catalog Client.
```suggestion
Isso permitirá que sua app faça chamadas para essa URL, especificamente. Por mais que você não tenha precisado colocá-la em seu código, é ela que é usada internamente pelo _Catalog Client_.
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/challenge.md
> +Você deve criar um Client `Search` que deve conter **apenas um método** chamado `productFullTextSearch` que receba apenas uma _string_ `term`. O Client deve chamar a API de Search, retornando uma lis
```suggestion
Você deve criar um _Client_ `Search` que deve conter **apenas um método** chamado `productFullTextSearch` que receba apenas uma _string_ `term`. O Client deve chamar a API de _Search_, retornando uma lista de produtos advindos da busca por este `term`.
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/metadata.json
> +  "description": "Utilize Clients para facilmente criar integrações com os módulos Core da VTEX",
```suggestion
  "description": "Utilize Clientes para facilmente criar integrações com os módulos Core da VTEX",
```

2020-09-17 19:59 UTC, juliarocha commented on courses/calling-commerce-apis/overview.md
> +Neste curso você aprenderá como encontrar e usar as APIs de Commerce da VTEX dentro de sua aplicação no VTEX IO, aprendendo sobre autorização e também como reusar Clients já feitos pela comunidade.
```suggestion
Neste curso você aprenderá como encontrar e usar as APIs de _Commerce_ da VTEX dentro de sua aplicação no VTEX IO, aprendendo sobre autorização e também como reusar _Clients_ já feitos pela comunidade. 
```

2020-09-17 20:16 UTC, lucis commented on courses/calling-commerce-apis/overview.md
> +Neste curso você aprenderá como encontrar e usar as APIs de Commerce da VTEX dentro de sua aplicação no VTEX IO, aprendendo sobre autorização e também como reusar Clients já feitos pela comunidade.
Done for all, @juliarocha  🚀

2020-09-18 16:54 UTC, juliarocha commented
😉 Strongly suggest merging [this PR](https://github.com/vtex/vtex-courses/pull/60) first

2020-09-18 18:09 UTC, juliarocha approved these changes
![approve](https://media.giphy.com/media/H3NGDz2Vxf54PL35u1/giphy.gif)

2020-09-19 19:24 UTC, merged